import os
import shutil
import time
import logging
from typing import Optional
import uuid

from datamodels import Manifest, CallbackEnvelope
from client import (
    fetch_manifest, 
    download_file, 
    send_callback, 
    build_callback, 
    get_query_fasta, 
    get_truth_file
)
from executor import run_veritas_sample, get_veritas_version
from exceptions import VeritasRunnerError
from status import StatusClass

logger = logging.getLogger(__name__)

FIFTEEN_MINUTES_S = 900  # Minimum remaining operational budget required to start a sample (ADR-13)


def _validate_prerequisites(attempt_id: str, output_dir: str) -> None:
    """Validates local system configuration before making network requests."""
    if not attempt_id or not attempt_id.strip():
        raise VeritasRunnerError(StatusClass.MISSING_ATTEMPT_ID, "attempt_id is missing or empty.")

    try:
        uuid.UUID(attempt_id)
    except ValueError:
        raise VeritasRunnerError(
            StatusClass.MISSING_ATTEMPT_ID,
            f"attempt_id is not a valid UUID: {attempt_id!r}"
        )

    if shutil.which("veritas") is None:
        raise VeritasRunnerError(StatusClass.CONFIG_ERROR, "'veritas' executable not found on PATH.")

    try:
        os.makedirs(output_dir, exist_ok=True)
    except OSError as e:
        raise VeritasRunnerError(StatusClass.CONFIG_ERROR, f"Could not create output directory '{output_dir}': {e}")

    if not os.access(output_dir, os.W_OK):
        raise VeritasRunnerError(StatusClass.CONFIG_ERROR, f"Output directory '{output_dir}' is not writable.")

    if not os.environ.get("PATHOEQA_API_URL"):
        raise VeritasRunnerError(StatusClass.CONFIG_ERROR, "PATHOEQA_API_URL environment variable is not set.")


def _validate_sample_output(sample_dir: str) -> None:
    """Verifies that mandatory execution outputs were generated by Veritas."""
    metrics_path = os.path.join(sample_dir, "metrics.tsv")
    if not os.path.exists(metrics_path):
        raise VeritasRunnerError(
            StatusClass.OUTPUT_INVALID, 
            f"Expected output file missing: {metrics_path}"
        )


def run_attempt(
    attempt_id: str, 
    workflow_run_id: int, 
    output_dir: str, 
    dry_run: bool = False
) -> CallbackEnvelope:
    """
    Main orchestration entrypoint for processing an attempt.
    Returns the final terminal CallbackEnvelope.
    """
    start_time = time.time()
    veritas_ver = get_veritas_version()
    
    logger.info("Starting attempt execution attempt_id=%s workflow_run_id=%d dry_run=%s", attempt_id, workflow_run_id, dry_run)

    try:
        # Phase 1: Environment validation & Manifest retrieval
        _validate_prerequisites(attempt_id, output_dir)
        manifest: Manifest = fetch_manifest(attempt_id)

        # Notify PathoEQA that preflight checks passed and processing is starting
        start_evt = build_callback(
            attempt_id=attempt_id,
            workflow_run_id=workflow_run_id,
            event_type="attempt_started",
            payload={"veritas_version": veritas_ver}
        )
        send_callback(start_evt)

        # Dry run handler
        if dry_run:
            logger.info("Dry run mode active. Skipping downloads and execution.")
            dry_run_evt = build_callback(
                attempt_id=attempt_id,
                workflow_run_id=workflow_run_id,
                event_type="attempt_completed",
                payload={
                    "dry_run": True,
                    "duration_ms": int((time.time() - start_time) * 1000),
                    "veritas_version": veritas_ver,
                }
            )
            send_callback(dry_run_evt)
            return dry_run_evt

        # Phase 2: Sequential Sample Processing
        completed_count = 0
        total_samples = len(manifest.samples)
        is_partial = False
        last_error: Optional[VeritasRunnerError] = None

        for sample in manifest.samples:
            elapsed = time.time() - start_time
            remaining_time = manifest.operational_deadline_seconds - elapsed

            # Deadline check: enforce 15-minute buffer before starting a new sample
            if remaining_time < FIFTEEN_MINUTES_S:
                logger.warning(
                    "Operational deadline approaching (%ds elapsed, %ds remaining). Stopping remaining samples as Partial.",
                    int(elapsed),
                    int(remaining_time)
                )
                is_partial = True
                break

            sample_dir = os.path.join(output_dir, sample.sample_run_id)
            os.makedirs(sample_dir, exist_ok=True)

            # Emit sample_started checkpoint
            send_callback(build_callback(
                attempt_id=attempt_id,
                workflow_run_id=workflow_run_id,
                event_type="sample_started",
                sample_run_id=sample.sample_run_id
            ))

            try:
                # 1. Download Query FASTA
                q_fasta = get_query_fasta(sample)
                q_path = os.path.join(sample_dir, "query.fasta")
                download_file(q_fasta.url, q_path, q_fasta.sha256, q_fasta.size)

                # 2. Download Truth Package components
                paths = {}
                for role, filename in [
                    ("reference_fasta", "reference.fa"),
                    ("truth_vcf", "truth.vcf.gz"),
                    ("rtg_sdf", "rtg_sdf.tar.gz")
                ]:
                    f_info = get_truth_file(sample, role)
                    dest = os.path.join(sample_dir, filename)
                    download_file(f_info.url, dest, f_info.sha256, f_info.size)
                    paths[role] = dest

                # 3. Execute Veritas CLI
                run_veritas_sample(
                    sample_dir=sample_dir,
                    query_fasta=q_path,
                    reference_fa=paths["reference_fasta"],
                    truth_vcf=paths["truth_vcf"],
                    rtg_reference=paths["rtg_sdf"],
                    timeout_seconds=manifest.hard_timeout_seconds,
                )

                # 4. Validate output integrity
                _validate_sample_output(sample_dir)
                completed_count += 1

                # Emit sample_completed checkpoint
                send_callback(build_callback(
                    attempt_id=attempt_id,
                    workflow_run_id=workflow_run_id,
                    event_type="sample_completed",
                    sample_run_id=sample.sample_run_id,
                    payload={"sample_order": sample.sample_order}
                ))

            except VeritasRunnerError as e:
                last_error = e
                logger.error("Sample %s failed: %s", sample.sample_run_id, e)
                
                # Emit sample_failed checkpoint and halt processing remaining samples
                send_callback(build_callback(
                    attempt_id=attempt_id,
                    workflow_run_id=workflow_run_id,
                    event_type="sample_failed",
                    sample_run_id=sample.sample_run_id,
                    payload={"error_class": e.failure_class, "message": str(e)}
                ))
                break

        duration_ms = int((time.time() - start_time) * 1000)

        # Phase 3: Final Attempt Status Reporting
        if last_error:
            # If a sample failed, mark attempt as failed
            failed_evt = build_callback(
                attempt_id=attempt_id,
                workflow_run_id=workflow_run_id,
                event_type="attempt_failed",
                payload={
                    "duration_ms": duration_ms,
                    "veritas_version": veritas_ver,
                    "completed_samples": completed_count,
                    "total_samples": total_samples,
                    "error_class": last_error.failure_class,
                    "message": str(last_error)
                }
            )
            send_callback(failed_evt)
            raise last_error

        elif is_partial:
            partial_evt = build_callback(
                attempt_id=attempt_id,
                workflow_run_id=workflow_run_id,
                event_type="attempt_partial",
                payload={
                    "duration_ms": duration_ms,
                    "veritas_version": veritas_ver,
                    "completed_samples": completed_count,
                    "total_samples": total_samples,
                    "reason": "Operational deadline reached before processing all samples."
                }
            )
            send_callback(partial_evt)
            return partial_evt

        else:
            completed_evt = build_callback(
                attempt_id=attempt_id,
                workflow_run_id=workflow_run_id,
                event_type="attempt_completed",
                payload={
                    "duration_ms": duration_ms,
                    "veritas_version": veritas_ver,
                    "completed_samples": completed_count,
                    "total_samples": total_samples
                }
            )
            send_callback(completed_evt)
            return completed_evt

    except VeritasRunnerError as e:
        duration_ms = int((time.time() - start_time) * 1000)
        unhandled_evt = build_callback(
            attempt_id=attempt_id,
            workflow_run_id=workflow_run_id,
            event_type="attempt_failed",
            payload={
                "duration_ms": duration_ms,
                "veritas_version": veritas_ver,
                "error_class": e.failure_class,
                "message": str(e)
            }
        )
        send_callback(unhandled_evt)
        raise

    except Exception as e:
        duration_ms = int((time.time() - start_time) * 1000)
        internal_evt = build_callback(
            attempt_id=attempt_id,
            workflow_run_id=workflow_run_id,
            event_type="attempt_failed",
            payload={
                "duration_ms": duration_ms,
                "veritas_version": veritas_ver,
                "error_class": StatusClass.INTERNAL_ERROR,
                "message": f"Unclassified error: {e}"
            }
        )
        send_callback(internal_evt)
        raise VeritasRunnerError(StatusClass.INTERNAL_ERROR, str(e))