import subprocess
import pysam
import sys
import os
import csv
import pandas as pd
import tempfile
from veritas.logger import logger

def fix_gsalign_vcf(input_vcf, output_vcf):
    """
    Fix GSAlign VCF issues before processing with pysam.

    Adds FILTER definition for '*' in header and removes problematic INFO/END fields.

    Args:
        input_vcf: Path to GSAlign VCF file
        output_vcf: Path to fixed VCF file
    """
    with open(input_vcf, "r") as fin, open(output_vcf, "w") as fout:
        header_done = False
        for line in fin:
            if line.startswith("##"):
                fout.write(line)
                # Add FILTER definition before the first #CHROM line
                if not header_done and line.startswith("##contig"):
                    fout.write(
                        '##FILTER=<ID=*,Description="All filters passed or filter information not available">\n'
                    )
                    header_done = True
            elif line.startswith("#CHROM"):
                # Make sure FILTER is defined before column headers
                if not header_done:
                    fout.write(
                        '##FILTER=<ID=*,Description="All filters passed or filter information not available">\n'
                    )
                fout.write(line)
            else:
                # Remove INFO/END field from data lines
                parts = line.strip().split("\t")
                if len(parts) >= 8:
                    info_field = parts[7]
                    # Remove END= from INFO field
                    info_parts = [
                        p for p in info_field.split(";") if not p.startswith("END=")
                    ]
                    parts[7] = ";".join(info_parts) if info_parts else "."
                fout.write("\t".join(parts) + "\n")

def process_gsalign_vcf(gsalign_vcf, sample_name, output_vcf):
    """
    Process GSAlign VCF to add FORMAT and sample columns, and fix FILTER field.

    Args:
        gsalign_vcf: Path to VCF generated by GSAlign
        sample_name: Sample name to use in the output VCF
        output_vcf: Path to output processed VCF

    Returns:
        Path to the processed VCF file
    """

    # Process VCF as text to avoid pysam END calculation warnings
    with open(gsalign_vcf, "r") as fin, open(output_vcf, "w") as fout:
        for line in fin:
            if line.startswith("##"):
                # Write header lines
                fout.write(line)
                # Add FILTER and FORMAT definitions after contig
                if line.startswith("##contig"):
                    fout.write('##FILTER=<ID=PASS,Description="All filters passed">\n')
                    fout.write(
                        '##FORMAT=<ID=GT,Number=1,Type=String,Description="Genotype">\n'
                    )
            elif line.startswith("#CHROM"):
                # Modify column header to add FORMAT and sample
                parts = line.strip().split("\t")
                # Remove existing columns after INFO (if any)
                parts = parts[:8]
                # Add FORMAT and sample columns
                parts.extend(["FORMAT", sample_name])
                fout.write("\t".join(parts) + "\n")
            else:
                # Process variant lines
                parts = line.strip().split("\t")
                if len(parts) >= 8:
                    # Change FILTER from * to PASS
                    parts[6] = "PASS"
                    # Remove INFO fields to avoid any END issues
                    parts[7] = "."
                    # Add FORMAT (GT) and sample genotype (1)
                    parts.extend(["GT", "1"])
                    fout.write("\t".join(parts) + "\n")

    # Compress and index the output VCF
    pysam.tabix_compress(output_vcf, output_vcf + ".gz", force=True)
    pysam.tabix_index(output_vcf + ".gz", preset="vcf", force=True)

    # Remove uncompressed file
    os.remove(output_vcf)

    return output_vcf + ".gz"


def compare(
    truth_vcf,
    query_vcf,
    output_dir,
    rtg_reference,
    primerd_bed=None,
    mask_bed=None,
    low_cov_truth_bed=None,
    low_cov_query_bed=None,
):
    """
    Compare truth and query VCFs using RTG Tools vcfeval.

    Args:
        truth_vcf: Path to truth VCF file
        query_vcf: Path to query VCF file
        output_dir: Directory to save output files
        rtg_reference: Path to RTG reference SDF directory
        primerd_bed: Path to primer BED file (optional)
        mask_bed: Path to mask BED file (optional)
        low_cov_truth_bed: Path to low coverage truth BED file (optional)
        low_cov_query_bed: Path to low coverage query BED file (optional)
    """
    rtg_dir = os.path.join(output_dir, "rtg")
    cmd = [
        "rtg",
        "vcfeval",
        "-b",
        truth_vcf,
        "-c",
        query_vcf,
        "-o",
        rtg_dir,
        "-t",
        rtg_reference,
    ]
    subprocess.run(cmd, check=True, stdout=subprocess.DEVNULL)

    def in_intervals(x, intervals):
        return any(int(start) <= int(x) <= int(end) for start, end in intervals)

    def process_vcf_file(
        vcf_file,
        vcf_output,
        origin_tag,
        primerd_bed,
        mask_bed,
        low_cov_truth_bed,
        low_cov_query_bed,
    ):
        try:
            with pysam.VariantFile(vcf_file) as template:
                header = template.header.copy()
            header.add_meta(
                "INFO",
                    items=[
                        ("ID", "TAG"),
                        ("Number", "1"),
                        ("Type", "String"),
                        (
                            "Description",
                            "Variant origin tag: TP=True Positive, FP=False Positive, FN=False Negative",
                        ),
                    ],
                )
            header.add_meta(
                "INFO",
                items=[
                    ("ID", "TYPE"),
                    ("Number", "1"),
                    ("Type", "String"),
                    (
                        "Description",
                        "Variant type: SNV=Single Nucleotide Variant, INDEL=Insertion or Deletion",
                    ),
                ],
            )
            header.add_meta(
                "INFO",
                items=[
                    ("ID", "BED"),
                    ("Number", "1"),
                    ("Type", "String"),
                    (
                        "Description",
                        "Variant in BED file: PRIMER=Bed with amplicon primer",
                    ),
                ],
            )
            with pysam.VariantFile(vcf_output, "w", header=header) as out_vcf:
                with pysam.VariantFile(vcf_file) as vcf:
                    for record in vcf:
                        new_record = out_vcf.new_record()
                        new_record.chrom = record.chrom
                        new_record.pos = record.pos
                        new_record.id = record.id
                        new_record.ref = record.ref
                        new_record.alts = record.alts
                        new_record.qual = record.qual
                        new_record.filter.clear()
                        for f in record.filter:
                            new_record.filter.add(f)
                        for key, value in record.info.items():
                            if key != "TAG" or key != "TYPE" or key != "BED":
                                new_record.info[key] = value
                        new_record.info["TAG"] = origin_tag
                        variant_type = (
                            "SNV"
                            if len(record.ref) == len(record.alts[0])
                            else "INDEL"
                        )
                        new_record.info["TYPE"] = variant_type
                        if primerd_bed and in_intervals(
                            record.pos, primerd_bed
                        ):
                            new_record.info["BED"] = "PRIMER"
                        if mask_bed and in_intervals(record.pos, mask_bed):
                            if not new_record.info.get("BED"):
                                new_record.info["BED"] = "MASK"
                            else:
                                new_record.info["BED"] += ",MASK"
                        if low_cov_truth_bed and in_intervals(
                            record.pos, low_cov_truth_bed
                        ):
                            if not new_record.info.get("BED"):
                                new_record.info["BED"] = "LOW_COV_TRUTH"
                            else:
                                new_record.info["BED"] += ",LOW_COV_TRUTH"
                        if low_cov_query_bed and in_intervals(
                            record.pos, low_cov_query_bed
                        ):
                            if not new_record.info.get("BED"):
                                new_record.info["BED"] = "LOW_COV_QUERY"
                            else:
                                new_record.info["BED"] += ",LOW_COV_QUERY"
                        out_vcf.write(new_record)
            pysam.tabix_index(vcf_output, preset="vcf", force=True)
        except Exception as e:
            logger.error(f"Error processing {vcf_file}: {e}")
            sys.exit(1)

    def merge_vcfs(tp_vcf, fp_vcf, fn_vcf, output_vcf):
        tp = pysam.VariantFile(tp_vcf)
        fp = pysam.VariantFile(fp_vcf)
        fn = pysam.VariantFile(fn_vcf)

        # Começa do header do TP
        merged_header = tp.header.copy()

        # Cria TAG identificador
        if "TAG" not in merged_header.info:
            merged_header.info.add("TAG", 1, "String", "Variant class: TP, FP, FN")

        # Função para copiar definições de INFO
        def add_missing_info(source_header):
            for key, info in source_header.info.items():
                if key not in merged_header.info and key != "END":
                    merged_header.info.add(
                        key, info.number, info.type, info.description
                    )

        # Unifica os headers dos outros arquivos
        add_missing_info(fp.header)
        add_missing_info(fn.header)

        out = pysam.VariantFile(output_vcf, "w", header=merged_header)

        # Lista final de chaves INFO (excluindo TAG e END)
        info_keys = [
            key for key in merged_header.info.keys() if key not in ["TAG", "END"]
        ]

        def write_records(vcf, tag):
            for record in vcf:
                # Create a new record with the merged header
                new_record = out.new_record()

                # Copy basic fields
                new_record.chrom = record.chrom
                new_record.pos = record.pos
                new_record.id = record.id
                new_record.ref = record.ref
                new_record.alts = record.alts
                new_record.qual = record.qual
                new_record.filter.clear()
                for filter_name in record.filter:
                    new_record.filter.add(filter_name)

                # Set the TAG
                new_record.info["TAG"] = tag

                # Copy existing INFO fields from the original record
                for key in record.info:
                    if key in info_keys and key != "END":
                        new_record.info[key] = record.info[key]

                # Set missing INFO fields to dot (.)
                for key in info_keys:
                    if key not in new_record.info:
                        # For missing fields, we need to handle them based on their type
                        if key in merged_header.info:
                            info_field = merged_header.info[key]
                            if info_field.number == 1 and info_field.type == "String":
                                new_record.info[key] = "."
                            elif (
                                info_field.number == 1 and info_field.type == "Integer"
                            ):
                                new_record.info[key] = -1  # or use None if you prefer
                            elif info_field.number == 1 and info_field.type == "Float":
                                new_record.info[key] = float("nan")
                            else:
                                new_record.info[key] = "."

                out.write(new_record)

        write_records(tp, "TP")
        write_records(fp, "FP")
        write_records(fn, "FN")

        out.close()

    process_vcf_file(
        f"{rtg_dir}/tp.vcf.gz",
        f"{rtg_dir}/tmp_tp.vcf.gz",
        "TP",
        primerd_bed,
        mask_bed,
        low_cov_truth_bed,
        low_cov_query_bed,
    )

    process_vcf_file(
        f"{rtg_dir}/fp.vcf.gz",
        f"{rtg_dir}/tmp_fp.vcf.gz",
        "FP",
        primerd_bed,
        mask_bed,
        low_cov_truth_bed,
        low_cov_query_bed,
    )

    process_vcf_file(
        f"{rtg_dir}/fn.vcf.gz",
        f"{rtg_dir}/tmp_fn.vcf.gz",
        "FN",
        primerd_bed,
        mask_bed,
        low_cov_truth_bed,
        low_cov_query_bed,
    )

    merge_vcfs(
        tp_vcf=f"{rtg_dir}/tmp_tp.vcf.gz",
        fp_vcf=f"{rtg_dir}/tmp_fp.vcf.gz",
        fn_vcf=f"{rtg_dir}/tmp_fn.vcf.gz",
        output_vcf=f"{rtg_dir}/tmp_merged.vcf.gz",
    )

    # Sort the merged VCF before indexing (merge writes in TP/FP/FN order, not position order)
    logger.info("Sorting merged VCF...")
    subprocess.run(
        [
            "bcftools",
            "sort",
            "-o",
            f"{output_dir}/truth_query.vcf.gz",
            "-O",
            "z",
            f"{rtg_dir}/tmp_merged.vcf.gz",
        ],
        check=True,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.DEVNULL,
    )

    # Index the final sorted VCF
    pysam.tabix_index(f"{output_dir}/truth_query.vcf.gz", preset="vcf", force=True)

    # Clean up temporary files
    os.remove(f"{rtg_dir}/tmp_tp.vcf.gz")
    os.remove(f"{rtg_dir}/tmp_tp.vcf.gz.tbi")
    os.remove(f"{rtg_dir}/tmp_fp.vcf.gz")
    os.remove(f"{rtg_dir}/tmp_fp.vcf.gz.tbi")
    os.remove(f"{rtg_dir}/tmp_fn.vcf.gz")
    os.remove(f"{rtg_dir}/tmp_fn.vcf.gz.tbi")
    os.remove(f"{rtg_dir}/tmp_merged.vcf.gz")


def get_bed_intervals(bed_file):
    """
    Read BED file and return a list of (start, end) tuples.

    Args:
        bed_file: Path to BED file

    Returns:
        List of (start, end) tuples
    """
    intervals = []
    with open(bed_file, "r") as f:
        reader = csv.reader(f, delimiter="\t")
        for row in reader:
            start = int(row[1])
            end = int(row[2])
            intervals.append((start, end))
    return intervals


def compute_metrics(tp, fp, fn):
    """
    Compute precision, recall, and F1-score safely.

    Args:
        tp: True positives count
        fp: False positives count
        fn: False negatives count

    Returns:
        Tuple of (precision, recall, f1_score)
    """

    def safe_div(a, b):
        return a / b if b > 0 else 0

    precision = safe_div(tp, tp + fp)
    recall = safe_div(tp, tp + fn)
    f1 = safe_div(2 * precision * recall, precision + recall)
    return precision, recall, f1


def in_bed_region(record, bed):
    """
    Check if record position falls within any BED interval.

    Args:
        record: pysam VariantRecord object
        bed: List of (start, end) tuples

    Returns:
        True if record position is in any interval, False otherwise
    """
    if not bed:
        return False
    pos = int(record.pos)
    return any(int(start) <= pos <= int(end) for start, end in bed)


def calc_metrics(
    vcf_file,
    has_primer_bed=False,
    has_mask_bed=False,
    has_low_cov_truth_bed=False,
    has_low_cov_query_bed=False,
):
    """
    Calculate SNV and INDEL metrics, with and without ignoring BED regions.

    Args:
        vcf_file: Path to VCF file with TAG and TYPE info
        has_primer_bed: Whether primer BED was provided
        has_mask_bed: Whether mask BED was provided
        has_low_cov_truth_bed: Whether low coverage truth BED was provided
        has_low_cov_query_bed: Whether low coverage query BED was provided

    Returns:
        Dictionary containing metrics for 'all' and specific BED regions
    """
    # Contagem completa (sem filtros)
    counts_all = {
        "SNV": {"TP": 0, "FP": 0, "FN": 0},
        "INDEL": {"TP": 0, "FP": 0, "FN": 0},
    }

    # Contagem ignorando regiões BED
    counts_primer = {
        "SNV": {"TP": 0, "FP": 0, "FN": 0},
        "INDEL": {"TP": 0, "FP": 0, "FN": 0},
    }
    counts_mask = {
        "SNV": {"TP": 0, "FP": 0, "FN": 0},
        "INDEL": {"TP": 0, "FP": 0, "FN": 0},
    }
    counts_low_cov_truth = {
        "SNV": {"TP": 0, "FP": 0, "FN": 0},
        "INDEL": {"TP": 0, "FP": 0, "FN": 0},
    }
    counts_low_cov_query = {
        "SNV": {"TP": 0, "FP": 0, "FN": 0},
        "INDEL": {"TP": 0, "FP": 0, "FN": 0},
    }
    with pysam.VariantFile(vcf_file) as vcf:
        for record in vcf:
            tag = record.info.get("TAG")
            if tag not in ("TP", "FP", "FN"):
                continue

            var_type = record.info.get("TYPE", "INDEL")  # default to INDEL se faltando
            bed_field = record.info.get("BED", "")
            bed_values = set(bed_field.split(",")) if bed_field else set()

            # 1) Sempre contar na métrica completa
            counts_all[var_type][tag] += 1

            # 2) Contagens beds específicas
            if "PRIMER" in bed_values:
                counts_primer[var_type][tag] += 1
            if "MASK" in bed_values:
                counts_mask[var_type][tag] += 1
            if "LOW_COV_TRUTH" in bed_values:
                counts_low_cov_truth[var_type][tag] += 1
            if "LOW_COV_QUERY" in bed_values:
                counts_low_cov_query[var_type][tag] += 1

    # Monta resultados
    def build_results(counts):
        res = {}
        for var_type, vals in counts.items():
            prec, rec, f1 = compute_metrics(vals["TP"], vals["FP"], vals["FN"])
            res[var_type] = {
                **vals,
                "Precision": prec,
                "Recall": rec,
                "F1-Score": f1,
            }
        return res

    return {
        "all": build_results(counts_all),
        "counts_primer": counts_primer if has_primer_bed else None,
        "counts_mask": counts_mask if has_mask_bed else None,
        "counts_low_cov_truth": counts_low_cov_truth if has_low_cov_truth_bed else None,
        "counts_low_cov_query": counts_low_cov_query if has_low_cov_query_bed else None,
    }


def save_metrics_tsv(metrics_dict, output_file):
    """
    Save metrics to TSV file.

    Args:
        metrics_dict: Dictionary of metrics from calc_metrics
        output_file: Path to output TSV file
    """

    rows = []

    # Parte ALL
    for var_type, data in metrics_dict["all"].items():
        rows.append({"Category": f"{var_type}", "Region": "ALL", **data})

    if metrics_dict.get("counts_primer"):
        for var_type, data in metrics_dict["counts_primer"].items():
            rows.append({"Category": f"{var_type}", "Region": "PRIMER BED", **data})

    if metrics_dict.get("counts_mask"):
        for var_type, data in metrics_dict["counts_mask"].items():
            rows.append({"Category": f"{var_type}", "Region": "MASK BED", **data})

    if metrics_dict.get("counts_low_cov_truth"):
        for var_type, data in metrics_dict["counts_low_cov_truth"].items():
            rows.append(
                {"Category": f"{var_type}", "Region": "LOW_COV_TRUTH BED", **data}
            )

    if metrics_dict.get("counts_low_cov_query"):
        for var_type, data in metrics_dict["counts_low_cov_query"].items():
            rows.append(
                {"Category": f"{var_type}", "Region": "LOW_COV_QUERY BED", **data}
            )

    df = pd.DataFrame(rows)
    df.to_csv(output_file, sep="\t", index=False)
